title: 'wesleyliao.github.io'
url: "https://wesleyliao.github.io"

header_pages:
  - index.md
  - cv.md
  - projects.md
  - contact.md

style: dark

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
