title: 'Wesley Liao | Applied AI Solutions'
description: "Leveraging AI and machine learning to unlock value in real estate, insurance, and retail."
url: "https://wesleyliao.com"

# Navigation pages
header_pages:
  - index.md
  - about.md
  - casestudies.md
  - contact.md

style: light # Or dark

footer: '© 2025 Wesley Liao | 235 Grand St 326, Jersey City, NJ, 07302 | <a href="https://www.linkedin.com/in/wesleyliao/">LinkedIn</a> | <a href="mailto:wesleyliao3@gmail.com">Email</a>'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console